<?php
$CONFIG = array (
  'instanceid' => 'ocu5d7tsglnz',
  'passwordsalt' => 'spSMFOzQQmn5sqfjwVQ0zGyCFS+rpy',
  'secret' => 'uvoNqvFpwYM/4kjN94TA08iakwiC4hBLB0njI6G2UxicBKON',
  'trusted_domains' => 
  array (
    0 => '192.168.0.1',
    1 => 'icloud.impressico.local',
  ),
  'datadirectory' => '/3T.B-Storage/ownclouddb/',
  'overwrite.cli.url' => 'http://icloud.impressico.local/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.5.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'set_database_password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'vinod.kumar',
  'mail_domain' => 'impressico.com',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpname' => 'vinod.kumar@impressico.com',
  'mail_smtppassword' => 'Vacant##',
  'mail_smtpport' => '587',
  'loglevel' => 3,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'tls',
);
