language: php
sudo: false

php:
  - 5.4

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

script:
  # Install dev dependencies
  - composer require --dev phpunit/phpunit ^4.8

  # Test lint
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd src/Tests
  - ../../vendor/bin/phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  
matrix:
matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0

  fast_finish: true
